import './globals.css'
import 'bootstrap/dist/css/bootstrap.css';
import '../node_modules/react-bootstrap/dist/react-bootstrap';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
